<AppManager>:
    HomeScreen:
        name: 'home_screen'
        id: home_screen
    ViewScreen:
        name: 'view_screen'
        id: view_screen
        
<HomeScreen>:
    BoxLayout:
        orientation: 'vertical'

        FileChoose:
            size_hint_y: 0.1
            on_release: root.choose()
            text: 'Carregue uma imagem'
            
        Image:
            id: image
            source: 'images/fundo.png'
            
        Button:
            id: submit_button
            disabled: True
            text: 'Submeter imagem'
            on_release: root.submit_img()
            size_hint_y: 0.15
        
<ViewScreen>:
    BoxLayout:
        orientation: 'vertical'

        BoxLayout:
            orientation:'horizontal'
            size_hint_y: 0.1

            Button:
                text: "Sem Marcações"
                on_release: root.change_original()

            Button:
                text:'Todas'
                on_release: root.change_geral()

            Button:
                text:'Lesionadas'
                on_release: root.change_lesioned()

            Button:
                text:'Negativas'
                on_release: root.change_negative()

        Label:
            id: img_result_text
            size_hint_y: 0.1
            font_size: 20
            orientation: 'center'
            canvas.before:
                Color:
                    rgba: 1, 1, 1, 1
                Rectangle:
                    size: self.size
                    pos: self.pos   # para pegar o objeto correto na imagem (sem isso a cor mudava no objeto errado)
            color: 0, 0, 0, 1


		AsyncImage:
            id: image2
            source: ''

        Button:
            text: 'Submeter nova imagem'
            on_release: root.change_screen()
			size_hint_y: 0.1

<LabelDropDown>:
    Button:
        text: 'Todas'
        size_hint_y: 0.2

    Button:
        text: 'Lesioned'
        size_hint_y: 0.2

    Button:
        text: 'Negative'
        size_hint_y: 0.2

<WaitingPopUp>:
    title: 'Aviso'
    size_hint_x: 0.6
    size_hint_y: 0.2

    BoxLayout:
        orientation: 'vertical'

        Label:
            text:'Aguarde enquanto processamos sua imagem, este popup \nfechará automaticamente ao finalizar o processamento'


# usar dp para medida de padding e sp para medida de fonte