<AppManager>:
    HomeScreen:
        name: "home_screen"
        id: home_screen
    ViewScreen:
        name: "view_screen"
        id: view_screen
        
<HomeScreen>:
    BoxLayout:
        orientation: "vertical"

        TooltipButton:
            id: file_choose
            size_hint_y: 0.1
            on_release: root.choose()
            text: "Carregar uma imagem"
            order: 0
            callback: root.change_btn_status
            tooltip_text: "Clique aqui para carregar sua imagem"
            
        Image:
            id: image
            source: "images/fundo.png"
            
        TooltipButton:
            id: submit_button
            text: "Processar sua imagem"
            size_hint_y: 0.1
            on_release: root.submit_img()
            disabled: True
            order: 1
            callback: root.change_btn_status
            tooltip_text: "Clique aqui para processar sua imagem"
        
<ViewScreen>:
    BoxLayout:
        orientation: "vertical"

        BoxLayout:
            orientation: "horizontal"
            size_hint_y: 0.1

            TooltipButton:
                text: "Sem Marcações"
                on_release: root.change_original()
                order: 0
                callback: root.change_btn_status
                tooltip_text: "Remover marcações"

            TooltipButton:
                text: "Todas"
                on_release: root.change_all()
                order: 1
                callback: root.change_btn_status
                tooltip_text: "Mostrar todas as marcações"

            TooltipButton:
                text: "Lesionadas"
                background_color: [1, 0, 0]
                on_release: root.change_lesioned()
                order: 2
                callback: root.change_btn_status
                tooltip_text: "Mostrar somente as lesionadas"

            TooltipButton:
                text: "Negativas"
                background_color: [0, 0.298, 1]
                on_release: root.change_negative()
                order: 3
                callback: root.change_btn_status
                tooltip_text: "Mostrar somente as negativas"

        Label:
            id: img_result_text
            size_hint_y: 0.1
            font_size: 20
            orientation: "center"
            canvas.before:
                Color:
                    rgba: 1, 1, 1, 1
                Rectangle:
                    size: self.size
                    pos: self.pos   # para pegar o objeto correto na imagem (sem isso a cor mudava no objeto errado)
            color: 0, 0, 0, 1
            markup: True


		AsyncImage:
            id: image2
            source: ''
            nocache: True

        TooltipButton:
            text: "Processar nova imagem"
			size_hint_y: 0.1
            on_release: root.change_screen()
            order: 4
            callback: root.change_btn_status
            tooltip_text: "Clique aqui para processar uma nova imagem"

<WaitingPopUp>:
    title: "Aviso"
    size_hint_x: 0.6
    size_hint_y: 0.2

    BoxLayout:
        orientation: "vertical"

        Label:
            text: "Aguarde enquanto processamos sua imagem. \nEste popup fechará automaticamente ao finalizar o processamento."
            halign: "center"


# usar dp para medida de padding e sp para medida de fonte